# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bayesQR_weighted_EM_cpp <- function(y, x, w, u, gamma_u, tau, mu0, sigma0, a0, b0) {
    .Call(`_tauBayesW_bayesQR_weighted_EM_cpp`, y, x, w, u, gamma_u, tau, mu0, sigma0, a0, b0)
}

MCMC_BWQR_AL <- function(y, X, w, tau = 0.5, n_mcmc = 50000L, burnin = 10000L, thin = 10L) {
    .Call(`_tauBayesW_MCMC_BWQR_AL`, y, X, w, tau, n_mcmc, burnin, thin)
}

MCMC_BWQR_AP <- function(y, X, w, tau = 0.5, n_mcmc = 20000L, burnin = 5000L, thin = 100L, w_scale = 2.0, b0_ = NULL, B0_ = NULL) {
    .Call(`_tauBayesW_MCMC_BWQR_AP`, y, X, w, tau, n_mcmc, burnin, thin, w_scale, b0_, B0_)
}

MCMC_BWQR_SL <- function(y, X, w, tau = 0.5, n_mcmc = 10000L, burnin = 2000L, thin = 10L, b0_ = NULL, B0_ = NULL) {
    .Call(`_tauBayesW_MCMC_BWQR_SL`, y, X, w, tau, n_mcmc, burnin, thin, b0_, B0_)
}

atualizarV_GIG <- function(y, X, w, beta, delta2, theta, sigma, N) {
    .Call(`_tauBayesW_atualizarV_GIG`, y, X, w, beta, delta2, theta, sigma, N)
}

atualizarBETA <- function(b, B, X, w, sigma, delta2, theta, v, y) {
    .Call(`_tauBayesW_atualizarBETA`, b, B, X, w, sigma, delta2, theta, v, y)
}

atualizarSIGMA <- function(c0, C0, X, w, beta, tau2, theta, v, y, n) {
    .Call(`_tauBayesW_atualizarSIGMA`, c0, C0, X, w, beta, tau2, theta, v, y, n)
}

bayesQRWeighted <- function(y, X, w, tau = 0.5, n_mcmc = 50000L, burnin_mcmc = 10000L, thin_mcmc = 10L) {
    .Call(`_tauBayesW_bayesQRWeighted`, y, X, w, tau, n_mcmc, burnin_mcmc, thin_mcmc)
}

